import type { ChapterDef } from './types';

// Map legend: . = floor, # = wall, D = desk, d = door/exit, C = chair, F = filing cabinet,
// B = bookshelf, T = table, W = window, P = pillar, R = rug, L = lamp, S = stairs

const CH1_MAP = [
  '####################',
  '#W....W....W....W..#',
  '#..DC..DC..DC......#',
  '#..C...C...C...F.F.#',
  '#..................#',
  '#..T.T.T...........#',
  '#..................d',
  '#..DC..DC..........#',
  '#..C...C...B.B.B.B.#',
  '#..................#',
  '#.....L............#',
  '#..T.......DC......#',
  '#..C.......C.......#',
  '#..................#',
  '####################',
];

const CH2_MAP = [
  '####################',
  '#....W.W.W.W.......#',
  '#..P.........P..F..#',
  '#..................#',
  '#.P....T.T....P....#',
  '#..................#',
  '#..P.........P.....#',
  '#..................#',
  '#.P..D.D.D.D..P....#',
  '#..................#',
  '#..P.........P.....#',
  '#..................d',
  '#.P....T.T....P....#',
  '#..................#',
  '####################',
];

const CH3_MAP = [
  '####################',
  '#W.....W.....W.....#',
  '#..F.F.F.F.........#',
  '#..................#',
  '#..T.T.T.T.T.......#',
  '#..................#',
  '#.......B.B.B......#',
  '#..................d',
  '#..D.D.D.D.........#',
  '#..C.C.C.C.........#',
  '#..................#',
  '#......L...L.......#',
  '#..T.T.T.T.T.......#',
  '#..................#',
  '####################',
];

const CH4_MAP = [
  '####################',
  '#W..W..W..W..W..W..#',
  '#.....T............#',
  '#.....C............#',
  '#..................#',
  '#..B.B.....B.B.....#',
  '#..................#',
  '#......D.D.........d',
  '#......C.C.........#',
  '#..................#',
  '#..L.......L.......#',
  '#..................#',
  '#..F.F.F.F.F.F.....#',
  '#..................#',
  '####################',
];

const CH5_MAP = [
  '####################',
  '#W.W.W.W.W.W.W.W.W.#',
  '#..P.........P.....#',
  '#.....T.T.T........#',
  '#.....C.C.C........#',
  '#..................#',
  '#..P...D.D...P.....#',
  '#......C.C.........d',
  '#..................#',
  '#..T.T.T.T.T.T.....#',
  '#..C.C.C.C.C.C.....#',
  '#..................#',
  '#..P.........P.....#',
  '#..................#',
  '####################',
];

const CH6_MAP = [
  '####################',
  '#W..W..W..W..W..W..#',
  '#..F.F.F.F.F.F.....#',
  '#..................#',
  '#..B.B.B.B.B.......#',
  '#..................#',
  '#..T.T.T...........#',
  '#..C.C.C...........d',
  '#..................#',
  '#.....L.....L......#',
  '#..................#',
  '#..D.D.D.D.D.......#',
  '#..C.C.C.C.C.......#',
  '#..................#',
  '####################',
];

const CH7_MAP = [
  '####################',
  '#W.W.W.W..d..W.W.W.#',
  '#..P...........P...#',
  '#.....T.T.T.T......#',
  '#..................#',
  '#.P..D.D.D.D.D..P..#',
  '#....C.C.C.C.C.....#',
  '#..................#',
  '#.T..T.T.T.T.T..T..#',
  '#.C..C.C.C.C.C..C..#',
  '#..................#',
  '#..P...........P...#',
  '#..................#',
  '#........L.........#',
  '####################',
];

export const CHAPTERS: ChapterDef[] = [
  {
    id: 1,
    title: 'Chapter 1',
    subtitle: 'The Newsroom',
    playerStart: { x: 4, y: 10 },
    map: CH1_MAP,
    exitPos: { x: 19, y: 6 },
    npcs: [
      {
        id: 'editor', name: 'Editor Harris', pos: { x: 3, y: 2 },
        bodyColor: '#5B3A29', hatColor: '#2C1810', skinColor: '#D4A574',
        talked: false,
        dialogue: [
          { speaker: 'Editor Harris', text: 'Good, you\'re here. We\'ve got a big story brewing.' },
          { speaker: 'Editor Harris', text: 'There\'s been a break-in at the Watergate complex. The Democratic National Committee offices.' },
          { speaker: 'Editor Harris', text: 'Something smells fishy. Five men were arrested — they had surveillance equipment.' },
          { speaker: 'Editor Harris', text: 'Your job: investigate. Talk to people. Gather evidence. Find the truth.', credBonus: 5 },
          { speaker: 'Editor Harris', text: 'Use ARROW KEYS or WASD to move. Press SPACE or E near people and objects to interact.' },
          { speaker: 'Editor Harris', text: 'Press N to open your evidence notebook. Your credibility meter matters — be careful with your reporting.' },
        ],
      },
      {
        id: 'colleague', name: 'Reporter Jane', pos: { x: 9, y: 2 },
        bodyColor: '#8B1A1A', hatColor: '#4A0E0E', skinColor: '#E8C39E',
        talked: false,
        dialogue: [
          { speaker: 'Reporter Jane', text: 'Have you been following the Pentagon Papers story? Daniel Ellsberg leaked classified documents last year.' },
          { speaker: 'Reporter Jane', text: 'They showed the government had been lying about the Vietnam War for years.' },
          { speaker: 'Reporter Jane', text: 'Public trust in the government has never been lower. People are angry.', evidenceGiven: 'pentagon_papers' },
        ],
      },
      {
        id: 'citizen', name: 'Veteran Mike', pos: { x: 6, y: 6 },
        bodyColor: '#556B2F', hatColor: '#2E3B1F', skinColor: '#C4A882',
        talked: false,
        dialogue: [
          { speaker: 'Veteran Mike', text: 'I served in Vietnam. The government sent us there based on lies.' },
          { speaker: 'Veteran Mike', text: 'Now Nixon talks about "law and order" but his people play dirty.' },
          { speaker: 'Veteran Mike', text: 'There\'s a culture of secrecy in this White House. Be careful, kid.', evidenceGiven: 'public_distrust' },
        ],
      },
    ],
    evidence: [
      { id: 'assignment', name: 'Press Assignment', description: 'Official assignment to investigate the Watergate break-in.', pos: { x: 14, y: 2 }, collected: false, glowColor: '#FFD700' },
      { id: 'news_clipping', name: 'News Clipping', description: 'Article about the five men arrested at the Watergate complex on June 17, 1972.', pos: { x: 14, y: 8 }, collected: false, glowColor: '#FFD700' },
    ],
    puzzle: {
      type: 'order',
      title: 'Timeline Challenge',
      instruction: 'Put these events in the correct chronological order:',
      items: [
        'Vietnam War escalation begins',
        'Pentagon Papers leaked (1971)',
        'Growing public distrust of government',
        'Watergate break-in (June 1972)',
      ],
      correctAnswer: [0, 1, 2, 3],
    },
    recap: [
      'The Vietnam War caused growing distrust in the U.S. government.',
      'The Pentagon Papers (1971) revealed that officials had lied about the war.',
      'President Nixon prioritized secrecy and political control.',
      'On June 17, 1972, five men were arrested breaking into the DNC offices at the Watergate complex.',
      'Journalists began investigating the connections behind the break-in.',
    ],
  },
  {
    id: 2,
    title: 'Chapter 2',
    subtitle: 'The Break-In',
    playerStart: { x: 1, y: 13 },
    map: CH2_MAP,
    exitPos: { x: 19, y: 11 },
    guardPatrols: [
      { path: [{ x: 5, y: 3 }, { x: 14, y: 3 }, { x: 14, y: 6 }, { x: 5, y: 6 }], speed: 0.03 },
      { path: [{ x: 3, y: 9 }, { x: 16, y: 9 }, { x: 16, y: 12 }, { x: 3, y: 12 }], speed: 0.025 },
    ],
    npcs: [
      {
        id: 'security', name: 'Night Guard Frank', pos: { x: 2, y: 1 },
        bodyColor: '#1B3A5C', hatColor: '#0D1F33', skinColor: '#D4A574',
        talked: false,
        dialogue: [
          { speaker: 'Night Guard Frank', text: 'I was on duty that night. Found tape on the door locks of the DNC offices.' },
          { speaker: 'Night Guard Frank', text: 'Someone had taped the locks open so they could get back in. Real amateur stuff.' },
          { speaker: 'Night Guard Frank', text: 'I called the police. They caught five men with cameras, wiretapping equipment, and cash.', evidenceGiven: 'taped_locks' },
        ],
      },
      {
        id: 'witness', name: 'Office Worker Diane', pos: { x: 16, y: 4 },
        bodyColor: '#4A235A', hatColor: '#2C1445', skinColor: '#E8C39E',
        talked: false,
        dialogue: [
          { speaker: 'Office Worker Diane', text: 'The burglars weren\'t ordinary thieves. They were trying to bug the phones.' },
          { speaker: 'Office Worker Diane', text: 'One of them, James McCord, was the security chief for Nixon\'s reelection committee — CREEP.' },
          { speaker: 'Office Worker Diane', text: 'That\'s the Committee to Re-Elect the President. Quite the name, right?', evidenceGiven: 'mccord_id' },
        ],
      },
    ],
    evidence: [
      { id: 'wiretap', name: 'Wiretap Device', description: 'Electronic surveillance device found at the DNC offices.', pos: { x: 8, y: 4 }, collected: false, glowColor: '#FF6347' },
      { id: 'cash_bundle', name: 'Cash Bundle', description: '$100 bills found on the burglars, traced to Nixon\'s campaign fund.', pos: { x: 12, y: 8 }, collected: false, glowColor: '#32CD32' },
      { id: 'address_book', name: 'Address Book', description: 'Burglar\'s address book containing the phone number of E. Howard Hunt, a White House consultant.', pos: { x: 5, y: 10 }, collected: false, glowColor: '#FFD700' },
    ],
    puzzle: {
      type: 'match',
      title: 'Connect the Evidence',
      instruction: 'Match each piece of evidence to what it proves:',
      items: ['Taped locks', 'Wiretap devices', 'Cash from campaign', 'McCord\'s ID'],
      pairs: ['Planned re-entry', 'Spying on Democrats', 'Campaign funding', 'CREEP connection'],
      correctAnswer: [0, 1, 2, 3],
    },
    recap: [
      'On June 17, 1972, five men broke into the Democratic National Committee headquarters.',
      'They carried wiretapping equipment and cameras to spy on the opposition.',
      'Burglar James McCord was directly employed by Nixon\'s reelection committee (CREEP).',
      'The burglars carried cash traceable to the Nixon campaign.',
      'An address book linked them to E. Howard Hunt, a White House consultant.',
    ],
  },
  {
    id: 3,
    title: 'Chapter 3',
    subtitle: 'Campaign Connections',
    playerStart: { x: 1, y: 7 },
    map: CH3_MAP,
    exitPos: { x: 19, y: 7 },
    npcs: [
      {
        id: 'informant', name: 'Source "Deep Throat"', pos: { x: 10, y: 1 },
        bodyColor: '#3C3C3C', hatColor: '#1A1A1A', skinColor: '#C4A882',
        talked: false,
        dialogue: [
          { speaker: '???', text: 'Follow the money. That\'s how you unravel this.' },
          { speaker: '???', text: 'The cash the burglars carried — it was laundered through a Mexican bank.' },
          { speaker: '???', text: 'CREEP had a secret slush fund. Hundreds of thousands of dollars for dirty tricks.', evidenceGiven: 'slush_fund' },
          { speaker: '???', text: 'This goes higher than you think. Much higher.' },
        ],
      },
      {
        id: 'campaign_worker', name: 'Ex-Staff Sarah', pos: { x: 5, y: 5 },
        bodyColor: '#CD853F', hatColor: '#8B6914', skinColor: '#FDBCB4',
        talked: false,
        dialogue: [
          { speaker: 'Ex-Staff Sarah', text: 'I used to work for the campaign. I left when things got... uncomfortable.' },
          { speaker: 'Ex-Staff Sarah', text: 'John Mitchell, the Attorney General himself, approved the break-in plan.' },
          { speaker: 'Ex-Staff Sarah', text: 'G. Gordon Liddy presented the plan. They called it "Operation Gemstone."', evidenceGiven: 'gemstone_plan' },
        ],
      },
    ],
    evidence: [
      { id: 'bank_records', name: 'Bank Records', description: 'Records showing $25,000 check deposited into burglar Bernard Barker\'s account, linked to Nixon\'s campaign.', pos: { x: 3, y: 2 }, collected: false, glowColor: '#32CD32' },
      { id: 'phone_logs', name: 'Phone Records', description: 'Calls between White House staff and the burglars in the weeks before the break-in.', pos: { x: 15, y: 5 }, collected: false, glowColor: '#FFD700' },
      { id: 'memo', name: 'Internal Memo', description: 'CREEP memo discussing "intelligence gathering" operations against the Democrats.', pos: { x: 8, y: 9 }, collected: false, glowColor: '#FF6347' },
    ],
    puzzle: {
      type: 'order',
      title: 'Chain of Command',
      instruction: 'Arrange the chain of command from top to bottom:',
      items: [
        'President Nixon',
        'AG John Mitchell (approved plan)',
        'G. Gordon Liddy (planned operation)',
        'E. Howard Hunt (recruited team)',
        'Burglars (carried out break-in)',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
    },
    recap: [
      'The Watergate burglars were funded by Nixon\'s campaign through a secret slush fund.',
      'Money was laundered through a Mexican bank to hide its origins.',
      'Attorney General John Mitchell approved the break-in plan, known as "Operation Gemstone."',
      'G. Gordon Liddy and E. Howard Hunt organized the operation.',
      'The break-in was not the work of rogue individuals — it was authorized at the highest levels.',
    ],
  },
  {
    id: 4,
    title: 'Chapter 4',
    subtitle: 'The Cover-Up',
    playerStart: { x: 1, y: 7 },
    map: CH4_MAP,
    exitPos: { x: 19, y: 7 },
    npcs: [
      {
        id: 'lawyer', name: 'Attorney Reynolds', pos: { x: 6, y: 3 },
        bodyColor: '#2F4F4F', hatColor: '#1A2E2E', skinColor: '#D4A574',
        talked: false,
        dialogue: [
          { speaker: 'Attorney Reynolds', text: 'After the arrests, the White House went into damage control mode.' },
          { speaker: 'Attorney Reynolds', text: 'Nixon\'s counsel John Dean coordinated the cover-up. Hush money was paid to the burglars.' },
          { speaker: 'Attorney Reynolds', text: 'Over $400,000 was paid to keep them quiet and prevent them from implicating higher-ups.', evidenceGiven: 'hush_money' },
        ],
      },
      {
        id: 'fbi_agent', name: 'Agent Cooper', pos: { x: 14, y: 10 },
        bodyColor: '#191970', hatColor: '#0A0A3C', skinColor: '#C4A882',
        talked: false,
        dialogue: [
          { speaker: 'Agent Cooper', text: 'Nixon tried to use the CIA to block our FBI investigation.' },
          { speaker: 'Agent Cooper', text: 'He told his chief of staff, H.R. Haldeman, to have the CIA tell us to back off.' },
          { speaker: 'Agent Cooper', text: 'They claimed it was a "national security" matter. It was obstruction of justice.', evidenceGiven: 'obstruction' },
        ],
      },
    ],
    evidence: [
      { id: 'payment_records', name: 'Payment Records', description: 'Records of secret payments to the Watergate burglars totaling over $400,000.', pos: { x: 3, y: 12 }, collected: false, glowColor: '#32CD32' },
      { id: 'shredded_docs', name: 'Shredded Documents', description: 'Partially reconstructed documents that were ordered destroyed by White House staff.', pos: { x: 10, y: 6 }, collected: false, glowColor: '#FF6347' },
    ],
    puzzle: {
      type: 'select',
      title: 'Identify the Cover-Up',
      instruction: 'Select ALL actions that were part of the Watergate cover-up:',
      items: [
        'Paying hush money to burglars',
        'Reporting the break-in to police',
        'Using CIA to block FBI investigation',
        'Publishing news articles about Vietnam',
        'Destroying evidence and documents',
        'Coaching witnesses to lie under oath',
        'Holding free and fair elections',
        'Firing investigators who got too close',
      ],
      correctAnswer: [0, 2, 4, 5, 7],
    },
    recap: [
      'After the break-in, the Nixon White House launched a massive cover-up.',
      'Over $400,000 in hush money was paid to the burglars to keep them silent.',
      'Nixon personally directed efforts to use the CIA to block the FBI investigation.',
      'Evidence was destroyed and witnesses were coached to lie.',
      'The cover-up was ultimately worse than the crime itself.',
    ],
  },
  {
    id: 5,
    title: 'Chapter 5',
    subtitle: 'The Investigation',
    playerStart: { x: 1, y: 7 },
    map: CH5_MAP,
    exitPos: { x: 19, y: 7 },
    npcs: [
      {
        id: 'senator', name: 'Senator Ervin', pos: { x: 8, y: 3 },
        bodyColor: '#4A4A4A', hatColor: '#2A2A2A', skinColor: '#D4A574',
        talked: false,
        dialogue: [
          { speaker: 'Senator Ervin', text: 'The Senate Watergate Committee was formed in February 1973.' },
          { speaker: 'Senator Ervin', text: 'Our hearings were televised nationally. The American people deserved to see the truth.' },
          { speaker: 'Senator Ervin', text: 'John Dean testified that Nixon knew about the cover-up. That was explosive.', evidenceGiven: 'dean_testimony' },
        ],
      },
      {
        id: 'journalist', name: 'Bob the Reporter', pos: { x: 14, y: 9 },
        bodyColor: '#8B6914', hatColor: '#5C4A0E', skinColor: '#E8C39E',
        talked: false,
        dialogue: [
          { speaker: 'Bob the Reporter', text: 'Woodward and Bernstein at the Washington Post broke this story wide open.' },
          { speaker: 'Bob the Reporter', text: 'They had a secret source — "Deep Throat" — who guided their investigation.' },
          { speaker: 'Bob the Reporter', text: 'The free press played a crucial role. Without journalism, this might have stayed buried.', evidenceGiven: 'press_role' },
        ],
      },
      {
        id: 'judge', name: 'Judge Sirica', pos: { x: 4, y: 9 },
        bodyColor: '#2C2C2C', hatColor: '#1A1A1A', skinColor: '#C4A882',
        talked: false,
        dialogue: [
          { speaker: 'Judge Sirica', text: 'I presided over the Watergate trial. I knew the burglars weren\'t telling the whole truth.' },
          { speaker: 'Judge Sirica', text: 'I pushed for maximum sentences to pressure them into cooperating.' },
          { speaker: 'Judge Sirica', text: 'McCord finally cracked. He wrote me a letter saying the defendants had been pressured to plead guilty and stay silent.', evidenceGiven: 'mccord_letter' },
        ],
      },
    ],
    evidence: [
      { id: 'testimony_transcript', name: 'Dean\'s Testimony', description: 'John Dean\'s testimony that Nixon discussed the cover-up at least 35 times.', pos: { x: 10, y: 6 }, collected: false, glowColor: '#FFD700' },
      { id: 'newspaper', name: 'Washington Post Article', description: 'Groundbreaking article linking the break-in to Nixon\'s inner circle.', pos: { x: 16, y: 3 }, collected: false, glowColor: '#32CD32' },
    ],
    puzzle: {
      type: 'match',
      title: 'Key Players',
      instruction: 'Match each person to their role in exposing Watergate:',
      items: ['Sen. Sam Ervin', 'Woodward & Bernstein', 'Judge John Sirica', 'John Dean'],
      pairs: ['Led Senate hearings', 'Investigated for the press', 'Pressured defendants to talk', 'Testified against Nixon'],
      correctAnswer: [0, 1, 2, 3],
    },
    recap: [
      'The Senate Watergate Committee held televised hearings in 1973.',
      'John Dean, Nixon\'s counsel, testified that the President knew about the cover-up.',
      'Journalists Woodward and Bernstein at the Washington Post investigated relentlessly.',
      'Judge Sirica pressured the burglars into revealing the truth about higher-ups.',
      'The combination of the press, Congress, and the courts drove the investigation forward.',
    ],
  },
  {
    id: 6,
    title: 'Chapter 6',
    subtitle: 'The Nixon Tapes',
    playerStart: { x: 1, y: 7 },
    map: CH6_MAP,
    exitPos: { x: 19, y: 7 },
    npcs: [
      {
        id: 'butterfield', name: 'Alexander Butterfield', pos: { x: 6, y: 3 },
        bodyColor: '#556B2F', hatColor: '#2E3B1F', skinColor: '#D4A574',
        talked: false,
        dialogue: [
          { speaker: 'Alexander Butterfield', text: 'I was a White House aide. During the Senate hearings, I was asked a question that changed everything.' },
          { speaker: 'Alexander Butterfield', text: 'I revealed that President Nixon had a secret taping system in the Oval Office.' },
          { speaker: 'Alexander Butterfield', text: 'Every conversation in that office was recorded. Every single one.', evidenceGiven: 'taping_system' },
        ],
      },
      {
        id: 'archivist', name: 'Archivist Williams', pos: { x: 14, y: 6 },
        bodyColor: '#8B4513', hatColor: '#5C2E0E', skinColor: '#E8C39E',
        talked: false,
        dialogue: [
          { speaker: 'Archivist Williams', text: 'Nixon fought tooth and nail to keep those tapes secret. He claimed "executive privilege."' },
          { speaker: 'Archivist Williams', text: 'The Supreme Court ruled 8-0 in United States v. Nixon that he had to hand them over.' },
          { speaker: 'Archivist Williams', text: 'One tape had an 18½-minute gap — someone had erased part of a critical conversation.', evidenceGiven: 'tape_gap' },
        ],
      },
    ],
    evidence: [
      { id: 'smoking_gun_tape', name: '"Smoking Gun" Tape', description: 'Recording from June 23, 1972 — just six days after the break-in — where Nixon orders the CIA to block the FBI investigation.', pos: { x: 4, y: 10 }, collected: false, glowColor: '#FF6347' },
      { id: 'supreme_court', name: 'Supreme Court Ruling', description: 'United States v. Nixon (1974): The President is not above the law. Unanimous 8-0 decision.', pos: { x: 12, y: 2 }, collected: false, glowColor: '#FFD700' },
    ],
    puzzle: {
      type: 'order',
      title: 'Tape Timeline',
      instruction: 'Put these tape-related events in order:',
      items: [
        'Nixon installs secret recording system',
        'Butterfield reveals tapes exist',
        'Nixon refuses to release tapes',
        'Supreme Court orders tapes released',
        '"Smoking Gun" tape proves Nixon\'s guilt',
      ],
      correctAnswer: [0, 1, 2, 3, 4],
    },
    recap: [
      'Alexander Butterfield revealed that Nixon secretly recorded all Oval Office conversations.',
      'Nixon fought to keep the tapes private, claiming executive privilege.',
      'The Supreme Court ruled unanimously in United States v. Nixon (1974) that he must release them.',
      'The "Smoking Gun" tape proved Nixon ordered the cover-up just six days after the break-in.',
      'An 18½-minute gap in one tape suggested deliberate erasure of evidence.',
    ],
  },
  {
    id: 7,
    title: 'Chapter 7',
    subtitle: 'Justice Prevails',
    playerStart: { x: 10, y: 12 },
    map: CH7_MAP,
    exitPos: { x: 10, y: 1 },
    npcs: [
      {
        id: 'congress_member', name: 'Rep. Jordan', pos: { x: 6, y: 5 },
        bodyColor: '#4A235A', hatColor: '#2C1445', skinColor: '#8B6914',
        talked: false,
        dialogue: [
          { speaker: 'Rep. Jordan', text: 'The House Judiciary Committee approved articles of impeachment against President Nixon.' },
          { speaker: 'Rep. Jordan', text: 'Article I: Obstruction of justice. Article II: Abuse of power. Article III: Contempt of Congress.' },
          { speaker: 'Rep. Jordan', text: '"My faith in the Constitution is whole, it is complete, it is total."', evidenceGiven: 'impeachment_articles' },
        ],
      },
      {
        id: 'historian', name: 'Professor Adams', pos: { x: 14, y: 5 },
        bodyColor: '#8B6914', hatColor: '#5C4A0E', skinColor: '#D4A574',
        talked: false,
        dialogue: [
          { speaker: 'Professor Adams', text: 'On August 9, 1974, Richard Nixon became the only U.S. president to resign from office.' },
          { speaker: 'Professor Adams', text: 'Vice President Gerald Ford became president and later pardoned Nixon.' },
          { speaker: 'Professor Adams', text: 'The legacy of Watergate: no one — not even the president — is above the law.' },
          { speaker: 'Professor Adams', text: 'It showed that the system of checks and balances works when people demand accountability.' },
        ],
      },
    ],
    evidence: [
      { id: 'resignation_letter', name: 'Resignation Letter', description: 'Nixon\'s official letter of resignation, dated August 9, 1974.', pos: { x: 10, y: 3 }, collected: false, glowColor: '#FFD700' },
      { id: 'final_report', name: 'Investigation Summary', description: 'Complete summary: 69 people indicted, 48 convicted, including top White House aides.', pos: { x: 3, y: 8 }, collected: false, glowColor: '#32CD32' },
    ],
    puzzle: {
      type: 'select',
      title: 'Lessons of Watergate',
      instruction: 'Select the TRUE statements about Watergate\'s lasting impact:',
      items: [
        'No one is above the law, including the president',
        'The scandal had no lasting impact on American politics',
        'A free press is essential for holding power accountable',
        'Presidents can claim executive privilege without limits',
        'Checks and balances between branches of government matter',
        'Public trust in government was permanently strengthened',
        'Transparency and accountability are vital to democracy',
        'The scandal led to reforms in campaign finance laws',
      ],
      correctAnswer: [0, 2, 4, 6, 7],
    },
    recap: [
      'The House Judiciary Committee approved three articles of impeachment against Nixon.',
      'Nixon resigned on August 9, 1974, rather than face almost certain removal.',
      '69 people were indicted and 48 were convicted for their roles in Watergate.',
      'Watergate proved that the American system of checks and balances can work.',
      'The lasting lesson: no one is above the law. Accountability, transparency, and a free press are the pillars of democracy.',
    ],
  },
];
